name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: situation1
      run:  pwd && ls
    - name: mkdir_build
      run:  mkdir -p build
    - name: cd_build
      run:  cd build
    - name: situation2
      run:  pwd .. && ls ..
    - name: cmake
      run: cmake ..
    - name: make
      run: make
    - name: run_tests
      run: ./tests
      
